### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by xmha97** [FineFindus/artem#1]
Can I use on Windows?

**Comment by FineFindus** [comment]
Yes, you can use it on windows. If you have `cargo` installed, you can install with `cargo install artem`. If you don't have cargo installed, [here is a tutorial on how to install it](https://doc.rust-lang.org/cargo/getting-started/installation.html).

Alternatively you can download the [artem-v0.6.0-x86_64-pc-windows-gnu-ubuntu-latest.zip](https://github.com/FineFindus/artem/releases/download/v0.6.0/artem-v0.6.0-x86_64-pc-windows-gnu-ubuntu-latest.zip) zip file from the [releases tab](https://github.com/FineFindus/artem/releases/) and extract the .exe file. After that you can use it in the terminal with `artem.exe` instead of `artem`.
