### ISSUE TITLE
replace "<span style="color: #000000"> </span>" with space character in html output. 

### ISSUE THREAD

**Issue by FOSSBOSS** [FineFindus/artem#13]
**Is your feature request related to a problem? Please describe.**
its not a real problem, nor a feature request, just a slight improvement... maybe. consider it.

**Describe the solution you'd like**
"</span style="color: #000000"> </ span>" is 37 characters to express 1 character (space) in a pre tag in html. 
with one image I'm sure its minimal. In my use case, Im creating frames in an animation, and those characters add up to extra megabytes. 
uses 
**Describe alternatives you've considered**
I write my animation frames as normal, and when I'm done I do system search & replace " </span style="color: #000000"> </ span>"
with " ", which yields the exact same visual but at a significantly reduced file size. I cut 34 frames down from 4.3MB to 2.3MB just now.
Its a space in a pre tag, pre will hand the spacing, and space character is clear, it doesn't need a span with color.  

- Ubuntu 20.04
- Shell:  Bash
- Version: 1.15
I dont know how to comment out html so I added a / and a space.

**Comment by FineFindus** [comment]
Thanks for the request. I have implemented it, so that no whitespace character will create a span-tag.
I actually saw an improved in one of the test files, which is now one-eighth of its original size, so that was an excellent request.

Also, your project sounds fascinating, could you show it to me once it is finished, it is always cool to see for what `artem` can be used?

**Comment by FOSSBOSS** [comment]
Im still working 14hour days so side projects are slow. 
here is a hand drawn animated ascii art I made long ago:
http://nanocluster.umeche.maine.edu/ascii/halloween
same js script  in the background, using artem to generate frames
