### ISSUE TITLE
Compile via Brew

### ISSUE THREAD

**Issue by DarrenPIngram** [FineFindus/artem#2]
**Is your feature request related to a problem? Please describe.**
Not a problem per se.

**Describe the solution you'd like**
Ability for this to be installed by "brew"

**Describe alternatives you've considered**
-

**Additional context**
-

**Information**

- OS: [e.g. Ubuntu 20.10]
- Shell: [e.g. Bash, PowerShell]
- Version: [e.g. 22]

For MacOS, but it could be used by other Linuxes too.

**Comment by FineFindus** [comment]
Thanks for the suggestion. I have not used brew yet, but I'll look into it

**Comment by FineFindus** [comment]
I have created a [brew tap](https://github.com/FineFindus/homebrew-tap), so `artem` is now installable with 
```bash
brew install finefindus/tap/artem
```
This also contains the man page and the tab completion files for bash, zsh and fish.
The tap should (hopefully) stay up to date, it will be updated from the same release workflow as all the others.

Since this is my first time working with homebrew, please consider reporting any issue that you encounter using the tap.
Thanks again for suggesting this feature.

**Comment by DarrenPIngram** [comment]
This worked first time. Thank you for going to the trouble of making this additional installation method.
